mcs: 
  dir: C:\Users\damie\OneDrive\Desktop\Damien\Wigeon_proj\HonoursRepo\output\mcs\run_Jul__5_12.41

baseline:
  dir: C:\Users\damie\OneDrive\Desktop\Damien\Wigeon_proj\HonoursRepo\output\baseline\run_Jun7_00.55
  name_pkl: Mission_class_07_June_00.55.pkl
