mcs: 
  dir: /home/damienkeijzer/Documents/Bachelor/Wigeon_proj/HonoursRepo/output/mcs/run_Aug__8_20.54_RBDO2

baseline:
  dir: /home/damienkeijzer/Documents/Bachelor/Wigeon_proj/HonoursRepo/output/baseline/run_Aug__7_23.29_D1
