mcs: 
  dir: C:\Users\damie\OneDrive\Desktop\Damien\Wigeon_proj\HonoursRepo\output\mcs\run_Aug_10_23.02

baseline:
  dir: C:\Users\damie\OneDrive\Desktop\Damien\Wigeon_proj\HonoursRepo\output\baseline\run_Aug_15_12.57
