services:
  # 1. Run this first to generate the data
  framework_mcs:
    build:
      context: .
      target: framework_mcs
    volumes:
      # Map a local folder './results' into the container
      - ./results_mcs:/app/output/mcs:z

  framework_baseline:
    build:
      context: .
      target: framework_baseline
    volumes:
      # Map a local folder './results' into the container
      - ./results_baseline:/app/output/baseline:z

