# pytest.ini

[pytest]
# Specify the test file patterns to discover
# You can use wildcards or directories
# Here, we include all files that start with "test_" and end with ".py"
# and exclude any files in the "venv" directory
python_files = test_*.py
testpaths = test/MCS*
console_output_style = progress


# Configure coverage settings
# Enables coverage analysis during test execution
# Requires the coverage package to be installed
# You can specify additional options for coverage if needed
# Here, we measure coverage for all project files except test files
# and generate an HTML report in the "coverage_html" directory
# You can customize the coverage options as per your project structure
# Refer to the pytest-cov documentation for more options

# https://pytest-cov.readthedocs.io/en/latest/config.html
; addopts = --cov= Final_optimization/Optimization.py
;                 Final_optimization/integration_class_ar_input.py
;                 Flight_performance/Flight_performance_final.py
;                 Validation_analysis
;                 range_simulation/range_analysis.py
;                 range_simulation/trips_file_creation.py
;    --cov-report=html:test/coverage
