# pytest.ini

[pytest]
python_files = test_*.py  
testpaths = tests/*  
console_output_style = progress
addopts= --ignore-glob=tests/Wigeon2021_tests/* --pdb -v -r P 

# https://pytest-cov.readthedocs.io/en/latest/config.html
;    --cov-report=html:test/coverage
